### POST request to create a new warehouse
POST http://localhost:8080/api/v1/carriers
Content-Type: application/json

{
  "cid": "CID#37",
  "company_name": "MELI",
  "address": "EcoTower",
  "locality_id": 1
}

### GET request to get an specific warehouse
GET http://localhost:8080/api/v1/localities/reportCarriers?id=1
Content-Type: application/json