### GET request to get a locality with report sellers
GET localhost:8080/api/v1/localities/reportSellers?id=1

### POST request to create a new locality
POST localhost:8080/api/v1/localities
Content-Type: application/json

{
    "id": 55,
    "locality_name": "Centro ventas",
    "province_name": "Bogotá",
    "country_name": "Colombia"
}

### POST request to create a new seller
POST localhost:8080/api/v1/sellers
Content-Type: application/json

{
  "id": 52,
  "name": "seller 1",
  "address": "calle 1 # 32-02",
  "telephone": "555-0055"
}