### GET request to get all products
GET http://localhost:8080/api/v1/products
Content-Type: application/json

### GET request to get an specific product
GET http://localhost:8080/api/v1/products/1
Content-Type: application/json

### POST request to create a new product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "product_code": "new product",
  "description": "new product",
  "width": 68.64,
  "height": 185.04,
  "length": 185.62,
  "net_weight": 2.93,
  "expiration_rate": 8.62,
  "recommended_freezing_temperature": -33.84,
  "freezing_rate": 0.62,
  "product_type_id": 6
  }
### "seller_id": 2

### PATCH request to update an specific product
PATCH http://localhost:8080/api/v1/products/8
Content-Type: application/json

{
  "id": 1,
  "product_code": "jajaj",
  "description": "Cambios realizados"
}

### DELETE request to delete an specific product
DELETE http://localhost:8080/api/v1/products/1
Content-Type: application/json